// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum DebugShape : int {
  DEBUG_SHAPE_NONE = 0,
  DEBUG_SHAPE_BOX = 1,
  DEBUG_SHAPE_CIRCLE = 2,
  DEBUG_SHAPE_LINE = 3,
  DebugShape_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DebugShape_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DebugShape_IsValid(int value);
constexpr DebugShape DebugShape_MIN = DEBUG_SHAPE_NONE;
constexpr DebugShape DebugShape_MAX = DEBUG_SHAPE_LINE;
constexpr int DebugShape_ARRAYSIZE = DebugShape_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DebugShape_descriptor();
template<typename T>
inline const std::string& DebugShape_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DebugShape>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DebugShape_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DebugShape_descriptor(), enum_t_value);
}
inline bool DebugShape_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DebugShape* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DebugShape>(
    DebugShape_descriptor(), name, value);
}
enum SkillInfo : int {
  SKILL_INFO_NONE = 0,
  SKILL_INFO_PUNCH = 1,
  SKILL_INFO_UPPERCUT = 2,
  SKILL_INFO_KICK = 3,
  SkillInfo_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  SkillInfo_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool SkillInfo_IsValid(int value);
constexpr SkillInfo SkillInfo_MIN = SKILL_INFO_NONE;
constexpr SkillInfo SkillInfo_MAX = SKILL_INFO_KICK;
constexpr int SkillInfo_ARRAYSIZE = SkillInfo_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SkillInfo_descriptor();
template<typename T>
inline const std::string& SkillInfo_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SkillInfo>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SkillInfo_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SkillInfo_descriptor(), enum_t_value);
}
inline bool SkillInfo_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SkillInfo* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SkillInfo>(
    SkillInfo_descriptor(), name, value);
}
enum MoveState : int {
  MOVE_STATE_NONE = 0,
  MOVE_STATE_IDLE = 1,
  MOVE_STATE_RUN = 2,
  MOVE_STATE_JUMP = 3,
  MoveState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MoveState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MoveState_IsValid(int value);
constexpr MoveState MoveState_MIN = MOVE_STATE_NONE;
constexpr MoveState MoveState_MAX = MOVE_STATE_JUMP;
constexpr int MoveState_ARRAYSIZE = MoveState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MoveState_descriptor();
template<typename T>
inline const std::string& MoveState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MoveState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MoveState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MoveState_descriptor(), enum_t_value);
}
inline bool MoveState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MoveState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MoveState>(
    MoveState_descriptor(), name, value);
}
enum ActionState : int {
  ACTION_STATE_NONE = 0,
  ACTION_STATE_SKILL = 1,
  ActionState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ActionState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ActionState_IsValid(int value);
constexpr ActionState ActionState_MIN = ACTION_STATE_NONE;
constexpr ActionState ActionState_MAX = ACTION_STATE_SKILL;
constexpr int ActionState_ARRAYSIZE = ActionState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ActionState_descriptor();
template<typename T>
inline const std::string& ActionState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ActionState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ActionState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ActionState_descriptor(), enum_t_value);
}
inline bool ActionState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ActionState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ActionState>(
    ActionState_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::DebugShape> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::DebugShape>() {
  return ::Protocol::DebugShape_descriptor();
}
template <> struct is_proto_enum< ::Protocol::SkillInfo> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::SkillInfo>() {
  return ::Protocol::SkillInfo_descriptor();
}
template <> struct is_proto_enum< ::Protocol::MoveState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::MoveState>() {
  return ::Protocol::MoveState_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ActionState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ActionState>() {
  return ::Protocol::ActionState_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
